### ISSUE TITLE
Default value on empty time stamps

### ISSUE THREAD

**Issue by OtavioLRS** [vasturiano/horizon-timeseries-chart#6]
Hey there!

First of all, thank you so much for this. Its really helping me out on my project. I tried to mess with your code, but couldn't figure it out how to do this properly, so here it goes.

When there's no data associated with a time stamp, it is ignored, right? That causes some weird shapes on some drawings. Also, when a series has a single time stamp with data, nothing is drawed at all. 

So, I was wondering if it would be possible to implement a ```.defaultData(object)``` of sorts. The ```object``` would be associated to every time stamp which has no data. That way, setting an ```object``` with ```val = 0``` could extinguish those weird shapes mencioned, given that no time stamp would be ignored, just setted as minimum value.

Anyway, thank you again!

**Comment by vasturiano** [comment]
@OtavioLRS thanks for reaching out. I'm glad the module is useful!

I would recommend to normalize your data before inputting it to the module. You should be able to assign default values (`0` in your case) to data points that are missing a value.
Concerning the single data point, this representation is mainly drawing connecting lines between data points. With a single data point there is no line to draw. I'd suggest surrounding the isolated data point with other `0` points so lines can be drawn. The framework cannot do that for you because it doesn't know the time bin/granularity of your data.
